apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: skyhigh-sample-schema
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  txMode: file
  devURLFrom:
    secretKeyRef:
      name: postgres-credentials
      key: dev-url
  credentials:
    scheme: postgres
    host: postgres-postgresql.database.svc.cluster.local
    user: postgres
    passwordFrom:
      secretKeyRef:
        key: POSTGRES_PASSWORD
        name: postgres-credentials
    database: postgres
    port: 5432
    parameters:
      sslmode: disable
  schema:
    sql: |
      -- Sample schema - testing
      CREATE TABLE IF NOT EXISTS sample_users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      );
      
      CREATE INDEX IF NOT EXISTS idx_sample_users_email ON sample_users(email);
