name: Database Schema CI (POC)
permissions:
  contents: read
  pull-requests: write
  
on:
  pull_request:
    paths:
      - 'apps/postgresql/atlasschema/**'
      - '.github/workflows/**'
      - 'bootstrap/**'

jobs:
  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Atlas CLI
        run: |
          curl -sSf https://atlasgo.sh | sh
          export PATH="$HOME/.atlas/bin:$PATH"
          echo "Atlas CLI installed:"
          atlas version
      - name: Install jq & yq
        run: |
          sudo wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          sudo wget -qO /usr/local/bin/jq \
            https://github.com/stedolan/jq/releases/latest/download/jq-linux64
          sudo chmod +x /usr/local/bin/jq
      - name: Extract SQL from YAML files
        run: |
          mkdir -p /tmp/schemas
          for schema_file in apps/postgresql/atlasschema/*.yaml; do
            if [ -f "$schema_file" ]; then
              echo "Processing $schema_file"
              schema_name=$(yq eval '.metadata.name' "$schema_file")
              yq eval '.spec.schema.sql' "$schema_file" > "/tmp/schemas/${schema_name}.sql"
              echo "Extracted SQL for $schema_name"
            fi
          done
      - name: Test schema syntax
        run: |
          DB_URL="postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable"
          DEV_URL="docker://postgres/latest"
          for sql_file in /tmp/schemas/*.sql; do
            if [ -f "$sql_file" ]; then
              echo "Testing $(basename $sql_file)..."
              atlas schema apply \
                --url "$DB_URL" \
                --to "file://$sql_file" \
                --dev-url "$DEV_URL" \
                --dry-run \
                --exclude lint
              echo "Linting $(basename $sql_file)..."  
              atlas schema lint \
                --dev-url "$DEV_URL" \
                --to "file://$sql_file" \
                --format '{{json .}}' | \
                jq -r '.diagnostics[]? | "**" + "'"$(basename "$sql_file")"'" + "**: " + .Text' \
                >> "$LINT_RESULTS" || true 
              echo "Schema syntax is valid for $(basename $sql_file)"
            fi
          done
          LINT_CONTENT=$(cat "$LINT_RESULTS" || true)
          LINT_CONTENT="${LINT_CONTENT//'%'/'%25'}"
          LINT_CONTENT="${LINT_CONTENT//$'\n'/'%0A'}"
          LINT_CONTENT="${LINT_CONTENT//$'\r'/'%0D'}"
          echo "lint_warnings=$LINT_CONTENT" >> $GITHUB_OUTPUT
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const lintWarnings = process.env.LINT_WARNINGS || '';
            const hasWarnings = lintWarnings.trim().length > 0;
            let comment = '## Database Schema Validation\n\n';
            comment += 'Schema syntax validation passed!\n\n';
            if (hasWarnings) {
              comment += '### Lint Warnings\n';
              comment += lintWarnings + '\n';
            } else {
              comment += 'No lint warnings found.\n';
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          LINT_WARNINGS: ${{ steps.schema_check.outputs.lint_warnings }}
