name: Validate Database Schema

on:
  pull_request:
    paths:
      - 'apps/postgresql/**'
      - 'bootstrap/**'

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Atlas CLI
        run: |
          curl -sSf https://atlasgo.sh | sh
          echo "Atlas CLI installed:"
          atlas version

      - name: Extract SQL from AtlasSchema YAML
        run: |
          awk '/sql: \|/{flag=1; next} /^[[:space:]]*[^[:space:]]/ && !/^[[:space:]]*--/ && !/^[[:space:]]*$/{if(flag && $0 !~ /^[[:space:]]*sql:/) exit} flag{print}' apps/          postgresql/schema1.yaml > test-schema.sql
          echo "Extracted SQL:"
          cat test-schema.sql

      - name: Lint SQL with Atlas
        run: |
          echo "Linting SQL with Atlas..."
          atlas schema lint --dev-url "postgres://postgres:test@localhost:5432/testdb" test-schema.sql

      - name: Validate Kubernetes YAML syntax
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          chmod +x kubeval
          find . -name "*.yaml" -not -path "./.github/*" | xargs ./kubeval
